// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.unige.idsi15;

import ch.unige.idsi15.Marker;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Marker_Roo_Configurable {
    
    declare @type: Marker: @Configurable;
    
}
